#!/usr/bin/env bash
# Generate a new shell script with shebang, comment, and copyright info.

script_name=${1:?Please provide a name for your script.}
shift
comment=$*
author='Jerry Q. Hacker'

cat > $script_name << END
#!/usr/bin/env bash
# $comment
# © $author $(date +%Y)


END
chmod 700 $script_name
